### ISSUE TITLE
V12 compatibility

### ISSUE THREAD

**Issue by drewg13** [TheLastScrub/delta-green-foundry-vtt-system-unofficial#115] opened 2024-05-27 13:59 UTC
You're going to want to drop a maximum core version of 11 on your most recent release (perhaps on all your older listed releases as well), as this system will successfully download or update in V12, but character sheets will not open.  You can just do this through the package management interface, so it should just take a minute.

Yes, users should wait to update core, but preventing them from installing a version that will not work will help also.

**Comment by jalensailin** [comment] 2024-05-27 17:24
Hey thanks for bringing this up. Will try to address this as soon as possible

**Comment by drewg13** [comment] 2024-06-01 13:20
Oof, it's still installable in V12, looks like that just pushed the version offered back to 1.4.3, the first version without a max set.  That means you probably need to put a max core of 11 on all your available releases, unfortunately.  To be clear, this is about preventing update-related support headaches as a fellow system dev, not about pressure to put out a compatible version.

**Comment by andrewbeard** [comment] 2024-06-07 15:04
I'm getting these warnings on v12:
```
The system "deltagreen" is using "gridDistance" which is deprecated in favor of "grid.distance".
The system "deltagreen" is using "gridUnits" which is deprecated in favor of "grid.units".
```

The fix for this (without breaking v11) involved defining it both the old way AND the new way. I can put up a PR in a bit.

**Comment by andrewbeard** [comment] 2024-06-08 02:14
Just added PR #117 to fix the grid warnings

**Comment by jalensailin** [comment] 2024-06-08 20:05
There are several issues that we identified in the transition to v12. We are currently working on those issues but it could still be some time.

**Comment by ericcberg** [comment] 2024-06-15 19:02
Putting this here in case it is not already known, but Agent sheets aren't working.

Error: An error occurred while rendering DeltaGreenActorSheet 60. One of original or other are not Objects!
    at Hooks.onError (foundry.js:630:24)
    at 🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:507:22)
    at 🎁Hooks.onError#lib-wrapper (listeners.js:138:11)
    at 🎁Hooks.onError#0 (libWrapper-wrapper.js:187:52)
    at foundry.js:5771:13Caused by: Error: One of original or other are not Objects!
    at mergeObject (foundry-esm.js:3324:13)
    at _mergeUpdate (foundry-esm.js:3388:14)
    at mergeObject (foundry-esm.js:3345:41)
    at _mergeUpdate (foundry-esm.js:3388:14)
    at mergeObject (foundry-esm.js:3345:41)
    at _mergeUpdate (foundry-esm.js:3388:14)
    at Object.mergeObject (foundry-esm.js:3345:41)
    at DeltaGreenActorSheet._render (foundry.js:5807:19)
    at DeltaGreenActorSheet._render (foundry.js:6548:17)
    at DeltaGreenActorSheet._render (foundry.js:7134:17)
    at DeltaGreenActorSheet.render (foundry.js:5769:10)
    at Token._onClickLeft2 (foundry.js:60839:17)
    at MouseInteractionManager.callback (foundry.js:30532:17)
    at #handleClickLeft2 (foundry.js:30755:15)
    at #handleLeftDown (foundry.js:30714:83)
    at #handlePointerDown (foundry.js:30679:58)
    at vh.notifyListeners (EventBoundary.ts:1454:26)
    at vh.notifyTarget (EventBoundary.ts:662:18)
    at vh.propagate (EventBoundary.ts:299:14)
    at vh.dispatchEvent (EventBoundary.ts:210:14)
    at vh.mapPointerDown (EventBoundary.ts:683:14)
    at vh.mapEvent (EventBoundary.ts:231:28)
    at ra.onPointerDown (EventSystem.ts:373:31)

**Comment by tobifroe** [comment] 2024-06-17 11:16
> There are several issues that we identified in the transition to v12. We are currently working on those issues but it could still be some time.

@jalensailin Will you create issues for the mentioned problems? Would love to help.

**Comment by jalensailin** [comment] 2024-06-17 12:30
We have already fixed them :). Just have to cut a release

**Comment by jalensailin** [comment] 2024-06-17 12:31
> Putting this here in case it is not already known, but Agent sheets aren't working.
> 
> Error: An error occurred while rendering DeltaGreenActorSheet 60. One of original or other are not Objects! at Hooks.onError (foundry.js:630:24) at 🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:507:22) at 🎁Hooks.onError#lib-wrapper (listeners.js:138:11) at 🎁Hooks.onError#0 (libWrapper-wrapper.js:187:52) at foundry.js:5771:13Caused by: Error: One of original or other are not Objects! at mergeObject (foundry-esm.js:3324:13) at _mergeUpdate (foundry-esm.js:3388:14) at mergeObject (foundry-esm.js:3345:41) at _mergeUpdate (foundry-esm.js:3388:14) at mergeObject (foundry-esm.js:3345:41) at _mergeUpdate (foundry-esm.js:3388:14) at Object.mergeObject (foundry-esm.js:3345:41) at DeltaGreenActorSheet._render (foundry.js:5807:19) at DeltaGreenActorSheet._render (foundry.js:6548:17) at DeltaGreenActorSheet._render (foundry.js:7134:17) at DeltaGreenActorSheet.render (foundry.js:5769:10) at Token._onClickLeft2 (foundry.js:60839:17) at MouseInteractionManager.callback (foundry.js:30532:17) at #handleClickLeft2 (foundry.js:30755:15) at #handleLeftDown (foundry.js:30714:83) at #handlePointerDown (foundry.js:30679:58) at vh.notifyListeners (EventBoundary.ts:1454:26) at vh.notifyTarget (EventBoundary.ts:662:18) at vh.propagate (EventBoundary.ts:299:14) at vh.dispatchEvent (EventBoundary.ts:210:14) at vh.mapPointerDown (EventBoundary.ts:683:14) at vh.mapEvent (EventBoundary.ts:231:28) at ra.onPointerDown (EventSystem.ts:373:31)

Can you please check with no modules enabled? Is this a fresh world or an existing world?

**Closed** 2024-06-18 02:25 UTC

**Comment by TheLastScrub** [comment] 2024-06-18 02:35
I was trying to see if I could make a release that was compatible with v11 and v12, but couldn't quite get it to be backwards compatible. I did however just publish the v12 compatible branch (v1.4.5) flagged as being only compatible with v12. I think this should resolve a couple of issues, but let us know if you are still seeing issues after upgrading to the latest system.
