### ISSUE TITLE
German Translation and Luck-Translate Error Message

### ISSUE THREAD

**Issue by KarstenW76** [TheLastScrub/delta-green-foundry-vtt-system-unofficial#100] opened 2023-12-22 11:37 UTC
Thank you for building up the system, so far (I'm new to Delta Green) it looks very good and seems to work fine. Thank you!

I see, you added some translations and I created (and already verified) a translation to German (DE-Deutsch). It would be awesome, if you add it:

[de.json](https://github.com/TheLastScrub/delta-green-foundry-vtt-system-unofficial/files/13752278/de.json)

With the translations I found a small error, one translation key is missing:
<img width="1036" alt="Bildschirmfoto 2023-12-22 um 12 31 14" src="https://github.com/TheLastScrub/delta-green-foundry-vtt-system-unofficial/assets/65510738/46bc601b-d8e7-4a72-ba65-c83097840e79">

The keys are already in the master (en.json) and I translated them to de.json. The execution of the luck roll in the Chat is correct via the both keys. But when hovering over the icon for Luck roll execution, the English "Roll Luck" is shown. I think, here must be a small mistake or missing key.

<img width="220" alt="Bildschirmfoto 2023-12-22 um 12 34 33" src="https://github.com/TheLastScrub/delta-green-foundry-vtt-system-unofficial/assets/65510738/05126eaf-9f57-4cfb-9f5f-4f365ab9d042">

Thank you for checking in advance! I wish you merry Christmas!
Kind regards, Karsten

**Comment by jalensailin** [comment] 2023-12-28 17:56
Thanks for the kind comments! We will definitely look into getting these changes integrated. Are you familiar with Git or GitHub at all? If you want, you could just open a Merge Request with the updated `json` but no worries if not.

**Comment by KarstenW76** [comment] 2024-01-10 16:01
Sorry, not so really, never merged anything. Would be perfect, if you check to add it by next ocation. For the meantime and myself I made up a module for the translation (for myself).
Thank you!

**Comment by TheLastScrub** [comment] 2024-01-29 01:12
@KarstenW76 @jalensailin 

I snuck this into v.1.4.2 since I was packing it up to address a bug Jalen fixed anyways. Let me know if you have any issues with it.

I couldn't reproduce the issue with the tool tip on the luck roll though. As far as I can tell there shouldn't even be a tooltip there in the first place. So not sure where that is coming from. I'm going to close this for now, but feel free to re-open an issue if there is more to add.

**Closed by TheLastScrub** 2024-01-29 01:12 UTC
